### ISSUE TITLE
compilation error: 5.15.36 - implicit declaration of function ‘alloc_inode_sb’

### ISSUE THREAD

**Issue by NetworkJack2** [sfjro/aufs-standalone#13]
Trying to compile on kernel 5.15.36, with AUFS patches from AUFS 5.15.5 branch

from the log

```
In file included from fs/aufs/aufs.h:52,
                 from fs/aufs/module.c:25:
fs/aufs/module.h: In function ‘au_cache_alloc_icntnr’:
fs/aufs/module.h:163:10: error: implicit declaration of function ‘alloc_inode_sb’ [-Werror=implicit-function-declaration]
  163 | { return alloc_inode_sb(sb, au_cache[AuCache_ICNTNR], GFP_NOFS); }
      |          ^~~~~~~~~~~~~~
fs/aufs/module.h:163:10: warning: returning ‘int’ from a function with return type ‘struct au_icntnr *’ makes pointer from integer without a cast [-Wint-conversion]
  163 | { return alloc_inode_sb(sb, au_cache[AuCache_ICNTNR], GFP_NOFS); }
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC      net/xfrm/xfrm_replay.o
  CC [M]  drivers/char/ipmi/ipmi_watchdog.o
In file included from fs/aufs/aufs.h:52,
                 from fs/aufs/sbinfo.c:24:
fs/aufs/module.h: In function ‘au_cache_alloc_icntnr’:
fs/aufs/module.h:163:10: error: implicit declaration of function ‘alloc_inode_sb’ [-Werror=implicit-function-declaration]
  163 | { return alloc_inode_sb(sb, au_cache[AuCache_ICNTNR], GFP_NOFS); }
      |          ^~~~~~~~~~~~~~
fs/aufs/module.h:163:10: warning: returning ‘int’ from a function with return type ‘struct au_icntnr *’ makes pointer from integer without a cast [-Wint-conversion]
  163 | { return alloc_inode_sb(sb, au_cache[AuCache_ICNTNR], GFP_NOFS); }
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sfjro** [comment]
GI Jack:
> Trying to compile on kernel 5.15.36, with AUFS patches from AUFS 5.15.5 b=
> ranch=0D
> =0D
> from the log=0D
> =0D
> ```=0D
> In file included from fs/aufs/aufs.h:52,=0D
>                  from fs/aufs/module.c:25:=0D
> fs/aufs/module.h: In function =E2=80=98au_cache_alloc_icntnr=E2=80=99:=0D=
>
> fs/aufs/module.h:163:10: error: implicit declaration of function =E2=80=98=
> alloc_inode_sb=E2=80=99 [-Werror=3Dimplicit-function-declaration]=0D
>   163 | { return alloc_inode_sb(sb, au_cache[AuCache_ICNTNR], GFP_NOFS); =
> }=0D
>       |          ^~~~~~~~~~~~~~=0D

alloc_inode_sb() was introduced in mainline v5.18-rc1, and aufs5.x-rcN
branch supports it.  Aufs5.15.5 should not contain such code calling
alloc_inode_sb().

Are you sure that your aufs5.15.5 code has alloc_inode_sb() call?


J. R. Okajima

**Comment by NetworkJack2** [comment]
After double checking, looks like there was an error in the PKGBUILD with an improperly set git checkout command

**Comment by sfjro** [comment]
GI Jack:
> Trying to compile on kernel 5.15.36, with AUFS patches from AUFS 5.15.5 b=
> ranch=0D
> =0D
> from the log=0D
> =0D
> ```=0D
> In file included from fs/aufs/aufs.h:52,=0D
>                  from fs/aufs/module.c:25:=0D
> fs/aufs/module.h: In function =E2=80=98au_cache_alloc_icntnr=E2=80=99:=0D=
>
> fs/aufs/module.h:163:10: error: implicit declaration of function =E2=80=98=
> alloc_inode_sb=E2=80=99 [-Werror=3Dimplicit-function-declaration]=0D
>   163 | { return alloc_inode_sb(sb, au_cache[AuCache_ICNTNR], GFP_NOFS); =
> }=0D
>       |          ^~~~~~~~~~~~~~=0D

alloc_inode_sb() was introduced in mainline v5.18-rc1, and aufs5.x-rcN
branch supports it.  Aufs5.15.5 should not contain such code calling
alloc_inode_sb().

Are you sure that your aufs5.15.5 code has alloc_inode_sb() call?


J. R. Okajima
