### ISSUE TITLE
Error compile on kernel 6.12.[5,6]

### ISSUE THREAD

**Issue by KrasNIX** [sfjro/aufs-standalone#50]
I get an error when building the kernel

```
  AR      init/built-in.a
  CC      fs/aufs/mvdown.o
  CC      fs/aufs/ioctl.o
  CC      fs/aufs/procfs.o
  CC      fs/aufs/plink.o
fs/aufs/i_op.c: In function ‘au_pin_hdir_set_owner’:
fs/aufs/i_op.c:641:52: error: ‘struct rw_semaphore’ has no member named ‘owner’
  641 |         atomic_long_set(&p->hdir->hi_inode->i_rwsem.owner, (long)task);
      |                                                    ^
  CC      fs/aufs/sysfs.o
make[4]: *** [scripts/Makefile.build:229: fs/aufs/i_op.o] Error 1
```
Preemption Model
  4. Fully Preemptible Kernel (Real-Time) (PREEMPT_RT) (NEW)

OS: Debian 12

Found that a patch is needed for the RT version of the kernel... 

But I can't find a patch for RT version 6.12

**Comment by sfjro** [comment]
KrasNIX:
> I get an error when building the kernel

It means you have enabled CONFIG_PREEMPT_RT which becomes available on
x86 very recently. And aufs6.12 is going to support it since today's
release. Try it please.


J. R. Okajima

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs6 GIT release (v6.13-rc5)
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 06 Jan 2025 07:15:45 +0900
Message-ID: ***@***.***>

o news
- - 6.12 x86 supports CONFIG_PREEMPT_RT

o bugfix
- - convert hlist_bl 1/2, bugfix, convert sbilist bit-spin lock into rwsem

o misc.
- - tiny, print an error at the end of remount
- - convert hlist_bl 2/2, convert sysrq handler call into schedule_work()
- - aufs-util.git fhsm, support concurrent invocation

J. R. Okajima

- ----------------------------------------
- - aufs6-linux.git#aufs6.6..aufs6.11.2
      aufs: tiny, print an error at the end of remount
      aufs: convert hlist_bl 1/2, bugfix, convert sbilist bit-spin lock into rwsem
      aufs: convert hlist_bl 2/2, convert sysrq handler call into schedule_work()

- - aufs6-linux.git#aufs6.12..aufs6.x-rcN
  Addition to above,
      aufs: 6.12 x86 supports CONFIG_PREEMPT_RT

- - aufs6-standalone.git
  ditto

- - aufs-util.git
      fhsm, support concurrent invocation

------- End of Blind-Carbon-Copy
