### ISSUE TITLE
Error compile on Kernel 7.1.2

### ISSUE THREAD

**Issue by benjibasson83** [sfjro/aufs-standalone#68]
Hi
I get an error when building the kernel after applying the BORE scheduler patch and AUFS patch on Linux 7.1.2.

Environment:

* Kernel: Linux 7.1.2
* Architecture: x86_64
* GCC: 15.2.0
* Distribution used for build: Porteus Linux

The kernel source builds correctly before applying the patches.

Applied patches:

* BORE scheduler
* AUFS

The build fails in `mm/shmem.c` with multiple parsing-related errors such as:

```text
mm/shmem.c: In function ‘shmem_evict_inode’:
mm/shmem.c:1447:21: error: invalid storage class for function ‘shmem_find_swap_entries’
```

This is followed by many cascading errors including:

* invalid storage class for function
* initializer element is not constant
* non-static declaration follows static declaration

The errors suggest that the compiler believes several functions are incorrectly nested inside `shmem_evict_inode()`.

I inspected the source around the reported location and noticed that the structure near the end of `shmem_evict_inode()` appears suspicious. The issue may be caused by:

* a missing `}` brace,
* a missing `#endif`,
* or an incorrect patch offset/application.

No `.rej` files were generated during patch application, but several `.orig` files exist:

```text
./kernel/sched/core.c.orig
./kernel/sched/fair.c.orig
./kernel/fork.c.orig
./fs/aufs/f_op.c.orig
```

I also verified that AUFS modifies global kernel/VFS headers including references in:

* `include/linux/fs.h`
* `include/linux/fs/super_types.h`

This may indicate an incompatibility between the current AUFS patchset and Linux 7.1.2 VFS/MM internals.

The problem does not appear to come from upstream `mm/shmem.c` itself, but rather from a structural corruption introduced after patching.

Has anyone successfully built AUFS on Linux 7.1.2, or is there an updated patchset compatible with the current VFS/MM changes?

No problem with 7.1.1
Cheers

**Comment by peabee** [comment]
> Has anyone successfully built AUFS on Linux 7.1.2

Yes - 7.1.2 built OK for me. No other patches.

**Comment by benjibasson83** [comment]
Thanks @peabee, that confirms it's not a general 7.1.2/AUFS incompatibility. BORE was never involved either — it doesn't touch mm/shmem.c at all.
The bug is in tmpfs-idr.patch (part of the aufs7 patchset). It adds an idr-based inode tracking block in shmem_evict_inode() but never closes it. Here's the broken result in mm/shmem.c:
	if (!sbinfo->idr_nouse && inode->i_ino) {
		mutex_lock(&sbinfo->idr_lock);
		idr_remove(&sbinfo->idr, inode->i_ino);
		mutex_unlock(&sbinfo->idr_lock);
	WARN_ON(inode->i_blocks);
	clear_inode(inode);
Four lines are added by the patch but the closing brace is missing, so the compiler parses everything after as nested inside shmem_evict_inode() — hence the cascading "invalid storage class" / "non-static declaration" errors.
Fix is adding one } after mutex_unlock(&sbinfo->idr_lock);:
	if (!sbinfo->idr_nouse && inode->i_ino) {
		mutex_lock(&sbinfo->idr_lock);
		idr_remove(&sbinfo->idr, inode->i_ino);
		mutex_unlock(&sbinfo->idr_lock);
	}
	WARN_ON(inode->i_blocks);
	clear_inode(inode);
This reproduces regardless of patch order or extra patches (BORE, etc.) — it's a bug in tmpfs-idr.patch itself. @peabee, did your successful 7.1.2 build include tmpfs-idr.patch?

**Comment by peabee** [comment]
We only apply these aufs patches:
for i in kbuild base standalone mmap; do

**Comment by sfjro** [comment]
Hello,
Sorry for my slow reply. I had to leave my apartment last week.

benjibasson83:
> The bug is in tmpfs-idr.patch (part of the aufs7 patchset). It adds an id=
> r-based inode tracking block in shmem_evict_inode() but never closes it. =
> Here's the broken result in mm/shmem.c:
	:::

You are right.
Taht is my bad. I failed my GIT work.
You can confirm it by
	$ git diff aufs7.0 aufs7.1 tmpfs-idr.patch
and it shows you need simple_xattrs_free() and shmem_free_inode() calls
too.

I will fix and test it, hopefully with linux-v7.2-rc[12].
The release will be next Monday.


J. R. Okajima

**Comment by sfjro** [comment]
"J. R. Okajima":
> and it shows you need simple_xattrs_free() and shmem_free_inode() calls
> too.

I missed again.
simple_xattrs_free() call is already there.


J. R. Okajima

**Comment by sfjro** [comment]
------- Blind-Carbon-Copy

From: "J. R. Okajima" ***@***.***>
To: ***@***.***
Subject: aufs[67] GIT release (v7.2-rc[12])
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-ID: ***@***.***>
Date: Mon, 13 Jul 2026 00:16:48 +0900
Message-ID: ***@***.***>

o bugfix
- - my GIT work failure, tmpfs-idr.patch in aufs7.1, reported by
  benjibasson83 on github.

o misc.
- - for linux-v7.2-rc1, suppress a warning about WQ_PERCPU
- - for linux-v7.2-rc1, new flag FSNOTIFY_EVENT_RENAME

J. R. Okajima

- ----------------------------------------

- - aufs6-linux.git
  nothing

- - aufs6-standalone.git
  nothing

- - aufs7-linux.git#aufs7.0..aufs7.1
  nothing

- - aufs7-linux.git#aufs7.x-rcN
      aufs: v7.2-rc1, suppress a warning about WQ_PERCPU
      aufs: v7.2-rc1, new flag FSNOTIFY_EVENT_RENAME

- - aufs7-standalone.git
  ditto

- - aufs-util.git
  nothing

------- End of Blind-Carbon-Copy
